const IMAGES = {
  headerLogo: "/images/header-logo.png",
  homeBanner: "/images/home/home-banner.jpg",
  iconBell: "/images/home/reminder-icon.png",
  iconLeft: "/images/home/left-button.png",
  iconRight: "/images/home/right-button.png",

  gameAg: "/images/slots/AG.png",
  gameAviatrix: "/images/slots/aviatrix.png",
  gameBtg: "/images/slots/BTG.png",
  gameCq9: "/images/slots/CQ9.png",
  gameDragon: "/images/slots/dragoon.png",
  gameFacai: "/images/slots/fa-chai.png",
  gameImperium: "/images/slots/imperium.png",
  gamejili: "/images/slots/jili.png",
  gameJoker: "/images/slots/joker.png",
  gameKingmaker: "/images/slots/kingmaker.png",
  gameLive22: "/images/slots/live22.png",
  gameNetEnt: "/images/slots/netent.png",
  gameNextSpin: "/images/slots/nextspin.png",
  gameNoLimit: "/images/slots/nolimit.png",
  gamePrag: "/images/slots/prag.png",
  gameRedTiger: "/images/slots/red-tiger.png",
  gameSpade: "/images/slots/spade.png",
  gameVpower: "/images/slots/Vpower.png",
  gameWm: "/images/slots/WM.png",
  featuredGame1: "/images/featuregames/1.png",
  featuredGame2: "/images/featuregames/2.png",
  featuredGame3: "/images/featuregames/3.png",
  featuredGame4: "/images/featuregames/4.png",

  upcomingBg1: "/images/upcomingevents/bg-card-1.png",
  upcomingBg2: "/images/upcomingevents/bg-card-2.png",
  iconIndia: "/images/upcomingevents/india.png",
  iconBangladesh: "/images/upcomingevents/bangladesh.png",
  iconIndonesia: "/images/upcomingevents/indonesia.png",
  iconThailand: "/images/upcomingevents/thailand.png",

  secIovation: "/images/footer/iovation-gray.png",
  secThreatMetrix: "/images/footer/threat-metrix.png",
  certBmm: "/images/footer/bmm-gray.png",
  certITechlab: "/images/footer/itechlab-gray.png",
  certGlobal: "/images/footer/global-gray.png",
  certGodaddy: "/images/footer/godaddy-gray.png",
  certPayout: "/images/footer/payouts-gray.png",
  payBitcoin: "/images/footer/ftr_bitcoin_grey.png",
  payUsdt: "/images/footer/ftr_usdt_grey.png",
  pay3: "/images/footer/1.png",
  payDuitnow: "/images/footer/2.png",
  pay5: "/images/footer/3.png",
  payTng: "/images/footer/4.png",
  payEezie: "/images/footer/eeziepay-gray.png",
  payHelp2pay: "/images/footer/help2pay-gray.png",
  payGrab: "/images/footer/6.png",
  payBoost: "/images/footer/5.png",

  btnDeposit: "/images/header/deposit-button.png",
  btnHistory: "/images/header/history-button.png",
  btnMsg: "/images/header/msg-button.png",
  btnTransfer: "/images/header/transfer-button.png",
  btnWithdraw: "/images/header/withdraw-button.png",

  sportsBanner: "/images/sports/sports-banner.jpg",
  sportsCMD: "/images/sports/CMD.png",
  sportsMaxbet: "/images/sports/maxbet.png",
  sportsSaba: "/images/sports/saba.png",

  casinoBanner: "/images/casino/casino-banner.jpg",
  casinoAG: "/images/casino/AG.png",
  casinoAllbet: "/images/casino/allbet.png",
  casinoBG: "/images/casino/BG.png",
  casinoDB: "/images/casino/DB.png",
  casinoDG: "/images/casino/DG.png",
  casinoEvolution: "/images/casino/evolution.png",
  casinoKing: "/images/casino/king.png",
  casinoPrag: "/images/casino/prag.png",
  casinoSexy: "/images/casino/sexy.png",
  casinoYB: "/images/casino/YB.png",

  slotsBanner: "/images/slots/slots-banner.jpg",

  fishBanner: "/images/fish/fishing-banner.jpg",
  fishBG: "/images/fish/BG.png",
  fishCQ9: "/images/fish/CQ9.png",
  fishDragoonSoft: "/images/fish/dragoonsoft.png",
  fishFacai: "/images/fish/fa-chai.png",
  fishJili: "/images/fish/jili.png",
  fishJoker: "/images/fish/joker.png",
  fishSpade: "/images/fish/spade.png",
  fishVpower: "/images/fish/Vpower.png",

  promo1Banner: "/images/promotions/promos-banner-example.png",

  downloadWM: "/images/download/WM.png",
  download918Kiss: "/images/download/918kiss.png",
  downloadMega888: "/images/download/mega888.png",
  downloadPlaytech: "/images/download/playtech.png",

  vipBanner: "/images/vip/NP99-VIP-bn.jpg",
  vipBronze: "/images/vip/bronze.png",
  vipDiamond: "/images/vip/diamond.png",
  vipGold: "/images/vip/gold.png",
  vipPlatinum: "/images/vip/platinum.png",
  vipSilver: "/images/vip/silver.png",

  contactTelegram: "/images/contactus/telegram-icon.png",
  contactLivechat: "/images/contactus/livechat-icon.png",

  flagChina2: "/images/flags/china-2.png",
  flagChina: "/images/flags/china.png",
  flagIndia2: "/images/flags/india-2.png",
  flagIndia: "/images/flags/india.png",
  flagJapan2: "/images/flags/japan-2.png",
  flagJapan: "/images/flags/japan.png",
  flagMalaysia2: "/images/flags/malaysia-2.png",
  flagMalaysia: "/images/flags/malaysia.png",
  flagNepal2: "/images/flags/nepal-2.png",
  flagNepal: "/images/flags/nepal.png",
  flagSouthKorea2: "/images/flags/south-korea-2.png",
  flagSouthKorea: "/images/flags/south-korea.png",
  flagUsa2: "/images/flags/usa-2.png",
  flagUsa: "/images/flags/usa.png",
  telegram: "/images/contactus/telegram-icon.png",
  liveChat: "/images/contactus/livechat-icon.png",

  signUpSuccess: "/images/signup/sign-up-succesful-icon.png",
  signUpWelcome: "/images/signup/signup-welcome-banner-PC.png",

  providerAG: "/images/provider/AG.png",
  providerAllbet:"/images/provider/allbet.png",
  providerAviatrix:"/images/provider/aviatrix.png",
  providerBG:"/images/provider/BG.png",
  providerBigTime:"/images/provider/big-time.png",
  providerCMD:"/images/provider/CMD.png",
  providerCQ9:"/images/provider/CQ9.png",
  providerDB:"/images/provider/DB.png",
  providerDG:"/images/provider/DG.png",
  providerDragoonsoft:"/images/provider/dragoonsoft.png",
  providerEvo:"/images/provider/evo.png",
  providerFachai:"/images/provider/fachai.png",
  providerImperium:"/images/provider/imperium.png",
  providerJili:"/images/provider/jili.png",
  providerJoker:"/images/provider/joker.png",
  providerKing:"/images/provider/king.png",
  providerKingmaker:"/images/provider/kingmaker.png",
  providerMaxbet:"/images/provider/maxbet.png",
  providerNetent:"/images/provider/netent.png",
  providerNextspin:"/images/provider/nextspin.png",
  providerNolimit:"/images/provider/nolimit.png",
  providerPrag:"/images/provider/prag.png",
  providerRedtiger:"/images/provider/red-tiger.png",
  providerSaba:"/images/provider/saba.png",
  providerSexy:"/images/provider/sexy.png",
  providerSpadegaming:"/images/provider/spadegaming.png",
  providerVpower:"/images/provider/Vpower.png",
  providerWM:"/images/provider/WM.png",
  providerYB:"/images/provider/YB.png"
};

export default IMAGES;
